rm ./build/autoconf_prepend-include/Makefile
rm ./demos/bombs/Makefile
rm ./demos/forty/Makefile
rm ./demos/fractal/Makefile
rm ./demos/life/Makefile
rm ./demos/poem/Makefile
rm ./demos/Makefile
rm ./locale/Makefile
rm ./misc/theme_test/Makefile
rm ./samples/animate/Makefile
rm ./samples/artprov/Makefile
rm ./samples/aui/Makefile
rm ./samples/calendar/Makefile
rm ./samples/caret/Makefile
rm ./samples/clipboard/Makefile
rm ./samples/collpane/Makefile
rm ./samples/combo/Makefile
rm ./samples/config/Makefile
rm ./samples/console/Makefile
rm ./samples/dataview/Makefile
rm ./samples/debugrpt/Makefile
rm ./samples/dialogs/Makefile
rm ./samples/dialup/Makefile
rm ./samples/display/Makefile
rm ./samples/dnd/Makefile
rm ./samples/docview/Makefile
rm ./samples/dragimag/Makefile
rm ./samples/drawing/Makefile
rm ./samples/erase/Makefile
rm ./samples/event/Makefile
rm ./samples/except/Makefile
rm ./samples/exec/Makefile
rm ./samples/font/Makefile
rm ./samples/fswatcher/Makefile
rm ./samples/grid/Makefile
rm ./samples/help/Makefile
rm ./samples/htlbox/Makefile
rm ./samples/html/about/Makefile
rm ./samples/html/help/Makefile
rm ./samples/html/helpview/Makefile
rm ./samples/html/printing/Makefile
rm ./samples/html/test/Makefile
rm ./samples/html/virtual/Makefile
rm ./samples/html/widget/Makefile
rm ./samples/html/zip/Makefile
rm ./samples/html/Makefile
rm ./samples/image/Makefile
rm ./samples/internat/Makefile
rm ./samples/ipc/Makefile
rm ./samples/joytest/Makefile
rm ./samples/keyboard/Makefile
rm ./samples/layout/Makefile
rm ./samples/listctrl/Makefile
rm ./samples/mdi/Makefile
rm ./samples/menu/Makefile
rm ./samples/minimal/Makefile
rm ./samples/notebook/Makefile
rm ./samples/popup/Makefile
rm ./samples/power/Makefile
rm ./samples/preferences/Makefile
rm ./samples/printing/Makefile
rm ./samples/propgrid/Makefile
rm ./samples/render/Makefile
rm ./samples/ribbon/Makefile
rm ./samples/richtext/Makefile
rm ./samples/sashtest/Makefile
rm ./samples/scroll/Makefile
rm ./samples/shaped/Makefile
rm ./samples/sockets/Makefile
rm ./samples/sound/Makefile
rm ./samples/splash/Makefile
rm ./samples/splitter/Makefile
rm ./samples/statbar/Makefile
rm ./samples/stc/Makefile
rm ./samples/svg/Makefile
rm ./samples/taborder/Makefile
rm ./samples/taskbar/Makefile
rm ./samples/text/Makefile
rm ./samples/thread/Makefile
rm ./samples/toolbar/Makefile
rm ./samples/treectrl/Makefile
rm ./samples/treelist/Makefile
rm ./samples/typetest/Makefile
rm ./samples/uiaction/Makefile
rm ./samples/validate/Makefile
rm ./samples/vscroll/Makefile
rm ./samples/widgets/Makefile
rm ./samples/wizard/Makefile
rm ./samples/wrapsizer/Makefile
rm ./samples/xrc/Makefile
rm ./samples/Makefile
rm ./src/zlib/Makefile
rm ./src/zlib/contrib/blast/Makefile
rm ./src/zlib/contrib/minizip/Makefile
rm ./src/zlib/contrib/puff/Makefile
rm ./src/zlib/contrib/untgz/Makefile
rm ./src/zlib/nintendods/Makefile
rm ./tests/benchmarks/Makefile
rm ./tests/Makefile
rm ./utils/emulator/src/Makefile
rm ./utils/emulator/Makefile
rm ./utils/execmon/Makefile
rm ./utils/helpview/src/Makefile
rm ./utils/helpview/Makefile
rm ./utils/hhp2cached/Makefile
rm ./utils/ifacecheck/src/Makefile
rm ./utils/screenshotgen/src/Makefile
rm ./utils/screenshotgen/Makefile
rm ./utils/wxrc/Makefile
rm ./utils/Makefile
rm ./gtk/Makefile
rm ./gtk/src/expat/expat/Makefile
rm ./gtk/src/expat/expat/doc/Makefile
rm ./gtk/src/expat/expat/examples/Makefile
rm ./gtk/src/expat/expat/lib/Makefile
rm ./gtk/src/expat/expat/tests/Makefile
rm ./gtk/src/expat/expat/tests/benchmark/Makefile
rm ./gtk/src/expat/expat/xmlwf/Makefile
rm ./gtk/utils/ifacecheck/src/Makefile
rm ./gtk/utils/Makefile
rm ./gtk/utils/emulator/Makefile
rm ./gtk/utils/emulator/src/Makefile
rm ./gtk/utils/execmon/Makefile
rm ./gtk/utils/helpview/Makefile
rm ./gtk/utils/helpview/src/Makefile
rm ./gtk/utils/hhp2cached/Makefile
rm ./gtk/utils/screenshotgen/Makefile
rm ./gtk/utils/screenshotgen/src/Makefile
rm ./gtk/utils/wxrc/Makefile
rm ./gtk/tests/Makefile
rm ./gtk/tests/benchmarks/Makefile
rm ./gtk/samples/xrc/Makefile
rm ./gtk/samples/wrapsizer/Makefile
rm ./gtk/samples/wizard/Makefile
rm ./gtk/samples/widgets/Makefile
rm ./gtk/samples/vscroll/Makefile
rm ./gtk/samples/validate/Makefile
rm ./gtk/samples/uiaction/Makefile
rm ./gtk/samples/typetest/Makefile
rm ./gtk/samples/treelist/Makefile
rm ./gtk/samples/treectrl/Makefile
rm ./gtk/samples/toolbar/Makefile
rm ./gtk/samples/thread/Makefile
rm ./gtk/samples/text/Makefile
rm ./gtk/samples/taskbar/Makefile
rm ./gtk/samples/taborder/Makefile
rm ./gtk/samples/svg/Makefile
rm ./gtk/samples/stc/Makefile
rm ./gtk/samples/statbar/Makefile
rm ./gtk/samples/splitter/Makefile
rm ./gtk/samples/splash/Makefile
rm ./gtk/samples/sound/Makefile
rm ./gtk/samples/sockets/Makefile
rm ./gtk/samples/shaped/Makefile
rm ./gtk/samples/scroll/Makefile
rm ./gtk/samples/sashtest/Makefile
rm ./gtk/samples/richtext/Makefile
rm ./gtk/samples/ribbon/Makefile
rm ./gtk/samples/render/Makefile
rm ./gtk/samples/propgrid/Makefile
rm ./gtk/samples/printing/Makefile
rm ./gtk/samples/preferences/Makefile
rm ./gtk/samples/power/Makefile
rm ./gtk/samples/popup/Makefile
rm ./gtk/samples/notebook/Makefile
rm ./gtk/samples/minimal/Makefile
rm ./gtk/samples/menu/Makefile
rm ./gtk/samples/mdi/Makefile
rm ./gtk/samples/listctrl/Makefile
rm ./gtk/samples/layout/Makefile
rm ./gtk/samples/keyboard/Makefile
rm ./gtk/samples/joytest/Makefile
rm ./gtk/samples/ipc/Makefile
rm ./gtk/samples/internat/Makefile
rm ./gtk/samples/image/Makefile
rm ./gtk/samples/html/zip/Makefile
rm ./gtk/samples/html/widget/Makefile
rm ./gtk/samples/html/virtual/Makefile
rm ./gtk/samples/html/test/Makefile
rm ./gtk/samples/html/printing/Makefile
rm ./gtk/samples/html/helpview/Makefile
rm ./gtk/samples/html/help/Makefile
rm ./gtk/samples/html/about/Makefile
rm ./gtk/samples/html/Makefile
rm ./gtk/samples/htlbox/Makefile
rm ./gtk/samples/help/Makefile
rm ./gtk/samples/grid/Makefile
rm ./gtk/samples/fswatcher/Makefile
rm ./gtk/samples/font/Makefile
rm ./gtk/samples/exec/Makefile
rm ./gtk/samples/except/Makefile
rm ./gtk/samples/event/Makefile
rm ./gtk/samples/erase/Makefile
rm ./gtk/samples/drawing/Makefile
rm ./gtk/samples/dragimag/Makefile
rm ./gtk/samples/docview/Makefile
rm ./gtk/samples/dnd/Makefile
rm ./gtk/samples/display/Makefile
rm ./gtk/samples/dialup/Makefile
rm ./gtk/samples/dialogs/Makefile
rm ./gtk/samples/debugrpt/Makefile
rm ./gtk/samples/dataview/Makefile
rm ./gtk/samples/console/Makefile
rm ./gtk/samples/config/Makefile
rm ./gtk/samples/combo/Makefile
rm ./gtk/samples/collpane/Makefile
rm ./gtk/samples/clipboard/Makefile
rm ./gtk/samples/caret/Makefile
rm ./gtk/samples/calendar/Makefile
rm ./gtk/samples/aui/Makefile
rm ./gtk/samples/artprov/Makefile
rm ./gtk/samples/animate/Makefile
rm ./gtk/samples/Makefile
rm ./gtk/samples/opengl/pyramid/Makefile
rm ./gtk/samples/opengl/penguin/Makefile
rm ./gtk/samples/opengl/isosurf/Makefile
rm ./gtk/samples/opengl/cube/Makefile
rm ./gtk/samples/opengl/Makefile
rm ./gtk/samples/mediaplayer/Makefile
rm ./gtk/demos/Makefile
rm ./gtk/demos/bombs/Makefile
rm ./gtk/demos/forty/Makefile
rm ./gtk/demos/fractal/Makefile
rm ./gtk/demos/life/Makefile
rm ./gtk/demos/poem/Makefile
rm ./Makefile
rm ./build2/Makefile
rm ./build2/utils/ifacecheck/src/Makefile
rm ./build2/utils/Makefile
rm ./build2/utils/emulator/Makefile
rm ./build2/utils/emulator/src/Makefile
rm ./build2/utils/execmon/Makefile
rm ./build2/utils/helpview/Makefile
rm ./build2/utils/helpview/src/Makefile
rm ./build2/utils/hhp2cached/Makefile
rm ./build2/utils/screenshotgen/Makefile
rm ./build2/utils/screenshotgen/src/Makefile
rm ./build2/utils/wxrc/Makefile
rm ./build2/src/expat/expat/Makefile
rm ./build2/src/expat/expat/doc/Makefile
rm ./build2/src/expat/expat/examples/Makefile
rm ./build2/src/expat/expat/lib/Makefile
rm ./build2/src/expat/expat/tests/Makefile
rm ./build2/src/expat/expat/tests/benchmark/Makefile
rm ./build2/src/expat/expat/xmlwf/Makefile
rm ./build2/samples/xrc/Makefile
rm ./build2/samples/wrapsizer/Makefile
rm ./build2/samples/wizard/Makefile
rm ./build2/samples/widgets/Makefile
rm ./build2/samples/vscroll/Makefile
rm ./build2/samples/validate/Makefile
rm ./build2/samples/uiaction/Makefile
rm ./build2/samples/typetest/Makefile
rm ./build2/samples/treelist/Makefile
rm ./build2/samples/treectrl/Makefile
rm ./build2/samples/toolbar/Makefile
rm ./build2/samples/thread/Makefile
rm ./build2/samples/text/Makefile
rm ./build2/samples/taskbar/Makefile
rm ./build2/samples/taborder/Makefile
rm ./build2/samples/svg/Makefile
rm ./build2/samples/stc/Makefile
rm ./build2/samples/statbar/Makefile
rm ./build2/samples/splitter/Makefile
rm ./build2/samples/splash/Makefile
rm ./build2/samples/sound/Makefile
rm ./build2/samples/sockets/Makefile
rm ./build2/samples/shaped/Makefile
rm ./build2/samples/scroll/Makefile
rm ./build2/samples/sashtest/Makefile
rm ./build2/samples/richtext/Makefile
rm ./build2/samples/ribbon/Makefile
rm ./build2/samples/render/Makefile
rm ./build2/samples/propgrid/Makefile
rm ./build2/samples/printing/Makefile
rm ./build2/samples/preferences/Makefile
rm ./build2/samples/power/Makefile
rm ./build2/samples/popup/Makefile
rm ./build2/samples/opengl/pyramid/Makefile
rm ./build2/samples/opengl/penguin/Makefile
rm ./build2/samples/opengl/isosurf/Makefile
rm ./build2/samples/opengl/cube/Makefile
rm ./build2/samples/opengl/Makefile
rm ./build2/samples/notebook/Makefile
rm ./build2/samples/minimal/Makefile
rm ./build2/samples/menu/Makefile
rm ./build2/samples/mediaplayer/Makefile
rm ./build2/samples/mdi/Makefile
rm ./build2/samples/listctrl/Makefile
rm ./build2/samples/layout/Makefile
rm ./build2/samples/keyboard/Makefile
rm ./build2/samples/joytest/Makefile
rm ./build2/samples/ipc/Makefile
rm ./build2/samples/internat/Makefile
rm ./build2/samples/image/Makefile
rm ./build2/samples/html/zip/Makefile
rm ./build2/samples/html/widget/Makefile
rm ./build2/samples/html/virtual/Makefile
rm ./build2/samples/html/test/Makefile
rm ./build2/samples/html/printing/Makefile
rm ./build2/samples/html/helpview/Makefile
rm ./build2/samples/html/help/Makefile
rm ./build2/samples/html/about/Makefile
rm ./build2/samples/html/Makefile
rm ./build2/samples/htlbox/Makefile
rm ./build2/samples/help/Makefile
rm ./build2/samples/grid/Makefile
rm ./build2/samples/fswatcher/Makefile
rm ./build2/samples/font/Makefile
rm ./build2/samples/exec/Makefile
rm ./build2/samples/except/Makefile
rm ./build2/samples/event/Makefile
rm ./build2/samples/erase/Makefile
rm ./build2/samples/drawing/Makefile
rm ./build2/samples/dragimag/Makefile
rm ./build2/samples/docview/Makefile
rm ./build2/samples/dnd/Makefile
rm ./build2/samples/display/Makefile
rm ./build2/samples/dialup/Makefile
rm ./build2/samples/dialogs/Makefile
rm ./build2/samples/debugrpt/Makefile
rm ./build2/samples/dataview/Makefile
rm ./build2/samples/console/Makefile
rm ./build2/samples/config/Makefile
rm ./build2/samples/combo/Makefile
rm ./build2/samples/collpane/Makefile
rm ./build2/samples/clipboard/Makefile
rm ./build2/samples/caret/Makefile
rm ./build2/samples/calendar/Makefile
rm ./build2/samples/aui/Makefile
rm ./build2/samples/artprov/Makefile
rm ./build2/samples/animate/Makefile
rm ./build2/samples/Makefile
rm ./build2/demos/Makefile
rm ./build2/demos/bombs/Makefile
rm ./build2/demos/forty/Makefile
rm ./build2/demos/fractal/Makefile
rm ./build2/demos/life/Makefile
rm ./build2/demos/poem/Makefile
rm ./build2/tests/Makefile
rm ./build2/tests/benchmarks/Makefile
rm ./build3/src/expat/expat/Makefile
rm ./build3/src/expat/expat/doc/Makefile
rm ./build3/src/expat/expat/examples/Makefile
rm ./build3/src/expat/expat/lib/Makefile
rm ./build3/src/expat/expat/tests/Makefile
rm ./build3/src/expat/expat/tests/benchmark/Makefile
rm ./build3/src/expat/expat/xmlwf/Makefile
rm ./build3/utils/ifacecheck/src/Makefile
rm ./build3/utils/Makefile
rm ./build3/utils/emulator/Makefile
rm ./build3/utils/emulator/src/Makefile
rm ./build3/utils/execmon/Makefile
rm ./build3/utils/helpview/Makefile
rm ./build3/utils/helpview/src/Makefile
rm ./build3/utils/hhp2cached/Makefile
rm ./build3/utils/screenshotgen/Makefile
rm ./build3/utils/screenshotgen/src/Makefile
rm ./build3/utils/wxrc/Makefile
rm ./build3/Makefile
rm ./build3/samples/xrc/Makefile
rm ./build3/samples/wrapsizer/Makefile
rm ./build3/samples/wizard/Makefile
rm ./build3/samples/widgets/Makefile
rm ./build3/samples/vscroll/Makefile
rm ./build3/samples/validate/Makefile
rm ./build3/samples/uiaction/Makefile
rm ./build3/samples/typetest/Makefile
rm ./build3/samples/treelist/Makefile
rm ./build3/samples/treectrl/Makefile
rm ./build3/samples/toolbar/Makefile
rm ./build3/samples/thread/Makefile
rm ./build3/samples/text/Makefile
rm ./build3/samples/taskbar/Makefile
rm ./build3/samples/taborder/Makefile
rm ./build3/samples/svg/Makefile
rm ./build3/samples/stc/Makefile
rm ./build3/samples/statbar/Makefile
rm ./build3/samples/splitter/Makefile
rm ./build3/samples/splash/Makefile
rm ./build3/samples/sound/Makefile
rm ./build3/samples/sockets/Makefile
rm ./build3/samples/shaped/Makefile
rm ./build3/samples/scroll/Makefile
rm ./build3/samples/sashtest/Makefile
rm ./build3/samples/richtext/Makefile
rm ./build3/samples/ribbon/Makefile
rm ./build3/samples/render/Makefile
rm ./build3/samples/propgrid/Makefile
rm ./build3/samples/printing/Makefile
rm ./build3/samples/preferences/Makefile
rm ./build3/samples/power/Makefile
rm ./build3/samples/popup/Makefile
rm ./build3/samples/opengl/pyramid/Makefile
rm ./build3/samples/opengl/penguin/Makefile
rm ./build3/samples/opengl/isosurf/Makefile
rm ./build3/samples/opengl/cube/Makefile
rm ./build3/samples/opengl/Makefile
rm ./build3/samples/notebook/Makefile
rm ./build3/samples/minimal/Makefile
rm ./build3/samples/menu/Makefile
rm ./build3/samples/mediaplayer/Makefile
rm ./build3/samples/mdi/Makefile
rm ./build3/samples/listctrl/Makefile
rm ./build3/samples/layout/Makefile
rm ./build3/samples/keyboard/Makefile
rm ./build3/samples/joytest/Makefile
rm ./build3/samples/ipc/Makefile
rm ./build3/samples/internat/Makefile
rm ./build3/samples/image/Makefile
rm ./build3/samples/html/zip/Makefile
rm ./build3/samples/html/widget/Makefile
rm ./build3/samples/html/virtual/Makefile
rm ./build3/samples/html/test/Makefile
rm ./build3/samples/html/printing/Makefile
rm ./build3/samples/html/helpview/Makefile
rm ./build3/samples/html/help/Makefile
rm ./build3/samples/html/about/Makefile
rm ./build3/samples/html/Makefile
rm ./build3/samples/htlbox/Makefile
rm ./build3/samples/help/Makefile
rm ./build3/samples/grid/Makefile
rm ./build3/samples/fswatcher/Makefile
rm ./build3/samples/font/Makefile
rm ./build3/samples/exec/Makefile
rm ./build3/samples/except/Makefile
rm ./build3/samples/event/Makefile
rm ./build3/samples/erase/Makefile
rm ./build3/samples/drawing/Makefile
rm ./build3/samples/dragimag/Makefile
rm ./build3/samples/docview/Makefile
rm ./build3/samples/dnd/Makefile
rm ./build3/samples/display/Makefile
rm ./build3/samples/dialup/Makefile
rm ./build3/samples/dialogs/Makefile
rm ./build3/samples/debugrpt/Makefile
rm ./build3/samples/dataview/Makefile
rm ./build3/samples/console/Makefile
rm ./build3/samples/config/Makefile
rm ./build3/samples/combo/Makefile
rm ./build3/samples/collpane/Makefile
rm ./build3/samples/clipboard/Makefile
rm ./build3/samples/caret/Makefile
rm ./build3/samples/calendar/Makefile
rm ./build3/samples/aui/Makefile
rm ./build3/samples/artprov/Makefile
rm ./build3/samples/animate/Makefile
rm ./build3/samples/Makefile
rm ./build3/demos/Makefile
rm ./build3/demos/bombs/Makefile
rm ./build3/demos/forty/Makefile
rm ./build3/demos/fractal/Makefile
rm ./build3/demos/life/Makefile
rm ./build3/demos/poem/Makefile
rm ./build3/tests/Makefile
rm ./build3/tests/benchmarks/Makefile
rm ./build4/utils/ifacecheck/src/Makefile
rm ./build4/utils/Makefile
rm ./build4/utils/emulator/Makefile
rm ./build4/utils/emulator/src/Makefile
rm ./build4/utils/execmon/Makefile
rm ./build4/utils/helpview/Makefile
rm ./build4/utils/helpview/src/Makefile
rm ./build4/utils/hhp2cached/Makefile
rm ./build4/utils/screenshotgen/Makefile
rm ./build4/utils/screenshotgen/src/Makefile
rm ./build4/utils/wxrc/Makefile
rm ./build4/Makefile
rm ./build4/samples/xrc/Makefile
rm ./build4/samples/wrapsizer/Makefile
rm ./build4/samples/wizard/Makefile
rm ./build4/samples/widgets/Makefile
rm ./build4/samples/vscroll/Makefile
rm ./build4/samples/validate/Makefile
rm ./build4/samples/uiaction/Makefile
rm ./build4/samples/typetest/Makefile
rm ./build4/samples/treelist/Makefile
rm ./build4/samples/treectrl/Makefile
rm ./build4/samples/toolbar/Makefile
rm ./build4/samples/thread/Makefile
rm ./build4/samples/text/Makefile
rm ./build4/samples/taskbar/Makefile
rm ./build4/samples/taborder/Makefile
rm ./build4/samples/svg/Makefile
rm ./build4/samples/stc/Makefile
rm ./build4/samples/statbar/Makefile
rm ./build4/samples/splitter/Makefile
rm ./build4/samples/splash/Makefile
rm ./build4/samples/sound/Makefile
rm ./build4/samples/sockets/Makefile
rm ./build4/samples/shaped/Makefile
rm ./build4/samples/scroll/Makefile
rm ./build4/samples/sashtest/Makefile
rm ./build4/samples/richtext/Makefile
rm ./build4/samples/ribbon/Makefile
rm ./build4/samples/render/Makefile
rm ./build4/samples/propgrid/Makefile
rm ./build4/samples/printing/Makefile
rm ./build4/samples/preferences/Makefile
rm ./build4/samples/power/Makefile
rm ./build4/samples/popup/Makefile
rm ./build4/samples/opengl/pyramid/Makefile
rm ./build4/samples/opengl/penguin/Makefile
rm ./build4/samples/opengl/isosurf/Makefile
rm ./build4/samples/opengl/cube/Makefile
rm ./build4/samples/opengl/Makefile
rm ./build4/samples/notebook/Makefile
rm ./build4/samples/minimal/Makefile
rm ./build4/samples/menu/Makefile
rm ./build4/samples/mediaplayer/Makefile
rm ./build4/samples/mdi/Makefile
rm ./build4/samples/listctrl/Makefile
rm ./build4/samples/layout/Makefile
rm ./build4/samples/keyboard/Makefile
rm ./build4/samples/joytest/Makefile
rm ./build4/samples/ipc/Makefile
rm ./build4/samples/internat/Makefile
rm ./build4/samples/image/Makefile
rm ./build4/samples/html/zip/Makefile
rm ./build4/samples/html/widget/Makefile
rm ./build4/samples/html/virtual/Makefile
rm ./build4/samples/html/test/Makefile
rm ./build4/samples/html/printing/Makefile
rm ./build4/samples/html/helpview/Makefile
rm ./build4/samples/html/help/Makefile
rm ./build4/samples/html/about/Makefile
rm ./build4/samples/html/Makefile
rm ./build4/samples/htlbox/Makefile
rm ./build4/samples/help/Makefile
rm ./build4/samples/grid/Makefile
rm ./build4/samples/fswatcher/Makefile
rm ./build4/samples/font/Makefile
rm ./build4/samples/exec/Makefile
rm ./build4/samples/except/Makefile
rm ./build4/samples/event/Makefile
rm ./build4/samples/erase/Makefile
rm ./build4/samples/drawing/Makefile
rm ./build4/samples/dragimag/Makefile
rm ./build4/samples/docview/Makefile
rm ./build4/samples/dnd/Makefile
rm ./build4/samples/display/Makefile
rm ./build4/samples/dialup/Makefile
rm ./build4/samples/dialogs/Makefile
rm ./build4/samples/debugrpt/Makefile
rm ./build4/samples/dataview/Makefile
rm ./build4/samples/console/Makefile
rm ./build4/samples/config/Makefile
rm ./build4/samples/combo/Makefile
rm ./build4/samples/collpane/Makefile
rm ./build4/samples/clipboard/Makefile
rm ./build4/samples/caret/Makefile
rm ./build4/samples/calendar/Makefile
rm ./build4/samples/aui/Makefile
rm ./build4/samples/artprov/Makefile
rm ./build4/samples/animate/Makefile
rm ./build4/samples/Makefile
rm ./build4/demos/Makefile
rm ./build4/demos/bombs/Makefile
rm ./build4/demos/forty/Makefile
rm ./build4/demos/fractal/Makefile
rm ./build4/demos/life/Makefile
rm ./build4/demos/poem/Makefile
rm ./build4/tests/Makefile
rm ./build4/tests/benchmarks/Makefile
