#!/bin/bash
dirs='--prefix=/data/data/com.termux/files/usr --exec-prefix=/data/data/com.termux/files/usr --sbindir=/data/data/com.termux/files/usr/bin --libexecdir=/data/data/com.termux/files/usr/lib --includedir=/data/data/com.termux/files/usr/include --oldincludedir=/data/data/com.termux/files/usr/include --localedir=/data/data/com.termux/files/usr/share/locale --datarootdir=/data/data/com.termux/files/usr/share'
../configure $dirs --with-gtk=2 --enable-cmdline --with-expat --enable-stl --with-sdl --enable-utf8 --enable-gui >& config.out
echo -ne '\a'
